### ISSUE TITLE
C++ with SDK 2.0 on RevA and B

### ISSUE THREAD

**Issue by debuuu** [nstbayless/playdate-cpp#1]
With the release of SDK 2.0 it seems the solutions in this repository no longer work. This seems at least partially down to the inclusion of the -nostartfiles flag (see: https://help.play.date/developer/os-2.0/#build-requirements), but could be other things at play. Sadly isn't as simple as removing this flag either.

I realise the repository hasn't been updated in a while, but thought I'd post in case you have any ideas for how to get C++ working again with the new SDK.

**Comment by metaphaseaudio** [comment]
@debuuu, please try the new workflow detailed in the readme. There's been a good amount of effort put into getting v2 working, and the feedback so far indicates that both RevA and B should be supported using this new system.

I'll keep this issue open for a week or so to give you a chance to try it out and respond with a 👍/👎.
